/* Trading engine rules and thresholds */

export const RULES = {
  MAX_POSITION_PCT: 0.045,
  STOP_LOSS_PCT: 0.04,
  TAKE_PROFIT_PCT: 0.15,
  TRAILING_STOP_PCT: 0.03,
  MIN_CASH_RESERVE_PCT: 0.10,
  MAX_SECTOR_PCT: 0.30,
  MAX_SINGLE_STOCK_PCT: 0.08,
  MIN_SCORE_BULL: 58,
  MIN_SCORE_BEAR: 72,
  MIN_SCORE_SIDEWAYS: 65,
  MOMENTUM_BOOST: 1.3,
  EARNINGS_PENALTY: 0.85,
  SCAN_INTERVAL: 10000,
  MAX_POSITIONS: 12,
  MAX_CORRELATED: 3,
  REBALANCE_THRESHOLD: 0.15,
};
